### PR TITLE
Add Visual Studio Code Support

### PR DESCRIPTION
**Pull request by Jake-Carter**
This PR adds Visual Studio Code support for all example projects.  The project files were generated using the [VSCode-Maxim](https://github.com/MaximIntegratedTechSupport/VSCode-Maxim) project, and are pre-release versions of the upcoming v1.3.0 release of that project.

**These projects require the MAXIM_PATH environment variable to be set properly**

Summary of changes:
- Add Arm GCC Tools to repo (v9.2.1 x86_64 linux)
- Add xPack RISC-V Tools to repo (v8.3.0-1.1 x64 linux)
- Make OpenOCD executable
- Add .vscode project folders
- Add readme file to all .vscode folders so user's can easily reference VSCode-Maxim-specific documentation

This PR will affect the following areas in documentation:
- https://github.com/MaximIntegratedAI/ai8x-synthesis#embedded-software-development-kit-sdk 
- https://github.com/MaximIntegratedAI/ai8x-synthesis#installation (Add note pointing to VSCode-Maxim installation instructions? https://github.com/MaximIntegratedTechSupport/VSCode-Maxim#installation)

Testing:
- [x] All example projects build on Windows and Ubuntu 20.04LTS (tested using WSL) except for the two projects attached.  These projects were not designed for the EVKIT and this will be addressed in a future release.  It should also be noted that most projects don't compile when targeting the cube camera, but the examples in general have not been designed for that BSP either.
- [x] Debugger functionality has been tested on Windows
- [ ] Debugger functionality has _not_ been tested on Linux, but the launch configuration is identical.  Point of failure is system-related setup issues that are covered in VSCode-Maxim setup documentation/[scripts](https://github.com/MaximIntegratedTechSupport/VSCode-Maxim/tree/main/dist/Ubuntu-20-04LTS).

### CODE REVIEW

**Comment by Jake-Carter** [comment]
[MAX78000_EvKit_V1_I2C_ADXL343.log](https://github.com/MaximIntegratedAI/MAX78000_SDK/files/8074363/MAX78000_EvKit_V1_I2C_ADXL343.log)
[MAX78000_EvKit_V1_SDHC_FTHR.log](https://github.com/MaximIntegratedAI/MAX78000_SDK/files/8074366/MAX78000_EvKit_V1_SDHC_FTHR.log)

**Review by lorne-maxim — COMMENTED** [review]
For the GNUTools you have the version number in base directory name, but for the xPacks you have the version number as a sub directory.  Is there are reason for the different structure between the two?  Is that the default structure they install too?  If not, what do you think about picking one way or the other?

**Comment by Jake-Carter** [comment]
> For the GNUTools you have the version number in base directory name, but for the xPacks you have the version number as a sub directory. Is there are reason for the different structure between the two? Is that the default structure they install too? If not, what do you think about picking one way or the other?

@lorne-maxim Yes, that's the default structure they install to.  I left them that way to minimize scripting overhead, but it's not hard to script them into a matching structure.

I would lean towards sub-directories, ie. change `arm-none-eabi-gcc-9.2.1` to `arm-none-eabi-gcc/9.2.1`.  This makes auto-detecting version numbers easier.

**Comment by Jake-Carter** [comment]
Closing this PR - VS Code support _on Github_ is dependent on the addition of toolchain binaries into the repo.  VS Code support is complete for the AI85/AI87 via the MaximSDK _installers_ until a cross-platofrm solution can be found for this repo.

**Pull request closed without merging**
