### PR TITLE
August 26, 2022 Release

### PR DESCRIPTION
**Pull request by lorne-maxim**
See README.md for list of changes.

### CODE REVIEW

**Comment by Jake-Carter** [comment]
The following PRs are captured by this one:
* https://github.com/Analog-Devices-MSDK/msdk/pull/83
  * All project readmes referencing "Makefile" have now been updated to point to "project.mk" instead.
  * A [link](https://github.com/Analog-Devices-MSDK/VSCode-Maxim/tree/develop#build-configuration) to documentation on the new system has been added to project.mk and Makefile.
  * The CAMERA variable is now exposed in this documentation
VSCode-Maxim readmes have been updated across the board with the new documentation. This removes the old documentation that was pointing to non-existent files.
  * The wording in project.mk and Makefile has been simplified in an effort to reduce confusion.
  * Fix HM0360 Camera driver flavors for AI85 board.mk and CameraIF example: https://github.com/Analog-Devices-MSDK/msdk/commit/eb14ed819ec2b0998053b8bffd00bff47a7b8952
  * Use HM0360_MONO and HM0360_COLOR in CameraIF example
  * Move CAMERA_MONO to board.mk

* https://github.com/Analog-Devices-MSDK/msdk/pull/82

* https://github.com/Analog-Devices-MSDK/msdk/pull/76

* https://github.com/Analog-Devices-MSDK/msdk/pull/64
  * Add SD card functionality.
  * Add image batch conversion utility for converting folders of raw images
  * Improve code organization
  * Improve console formatting and command registration
  * Improve documentation  
  
* https://github.com/Analog-Devices-MSDK/msdk/pull/58

**Comment by Jake-Carter** [comment]
@maximreza typo fixes have been pushed to MAX78000_SDK PR as well.

**Comment by Jake-Carter** [comment]
This PR is currently pending review of some additional Camera driver updates to bring in:
* https://github.com/Analog-Devices-MSDK/msdk/pull/96
* https://github.com/Analog-Devices-MSDK/Libraries-miscDrivers/pull/5

**Comment by Jake-Carter** [comment]
@lorne-maxim @rotx-maxim ready for final review

**Review by rotx-maxim — APPROVED** [review]

**Review by aniktash — APPROVED** [review]
sounds good

**Comment by Jake-Carter** [comment]
Thanks @rotx-maxim, @aniktash, merging now

**Pull request merged**
