### PR TITLE
2021-01-24 release.  See README.md for release notes.

### PR DESCRIPTION
**Pull request by lorne-maxim**

### CODE REVIEW

**Review by aniktash — COMMENTED** [review]
in TFT Demo example, TFT needs to be enabled by default for FTHR_RevA in make file

**Review by aniktash — COMMENTED** [review]
For demos that require TFT like faceid_evkit, cats-dogs-demo, snake_game_demo, I suggest to enable TFT by default for FTHR, and update the README to emphasis TFT is required.

**Comment by vicloginov** [comment]
> For demos that require TFT like faceid_evkit, cats-dogs-demo, snake_game_demo, I suggest to enable TFT by default for FTHR, and update the README to emphasis TFT is required.

Faceid_evkit, cats-dogs-demo can still run on Feather without TFT and report result on terminal. Snake game is different and Feather TFT is required to run it.

**Comment by vicloginov** [comment]
> For demos that require TFT like faceid_evkit, cats-dogs-demo, snake_game_demo, I suggest to enable TFT by default for FTHR, and update the README to emphasis TFT is required.

**Comment by vicloginov** [comment]
> in TFT Demo example, TFT needs to be enabled by default for FTHR_RevA in make file
Feather is not supplied with TFT, it may confuse user

**Review by vicloginov — APPROVED** [review]
Looks good!

**Pull request merged**
