### PR TITLE
Fix I2C driver for Feather; improve documentation

### PR DESCRIPTION
**Pull request by vicloginov**
Restored KWS20 demo functionality on Feather
Updated documentation

### CODE REVIEW

**Review by aniktash — COMMENTED** [review]
sounds good

**Review by rotx-maxim — DISMISSED** [review]

**Review by tchenot — CHANGES_REQUESTED** [review]
Regarding changes to 12c_reva.c
lines 77..79
i2c peripheral pointer is used before check for NULL pointer. This code should be moved after NULL pointer check.

**Comment by vicloginov** [comment]
> Regarding changes to 12c_reva.c
> lines 77..79
> i2c peripheral pointer is used before check for NULL pointer. This code should be moved after NULL pointer check.

I agree and will make a change

**Review by rotx-maxim — APPROVED** [review]

**Comment by tokuhira** [comment]
With this fix, I think the Camera IF example has also been fixed to work with the MAX78000FTHR. Thank you.

**Pull request merged**
